config/routes.rb
JurgensSmit::Application.routes.draw do

root :to => "home#index"

get "blog/index", :id => "blog"
 match "blog" => "blog#index"

get "home/index", :id => "home"
match "home" => "home#index"

match 'contact' => 'contact#new', :as => 'contact', :via => :get
match 'contact' => 'contact#create', :as => 'contact', :via => :post
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
<div class="alert alert-error alert-block">
<button type="button" class="close" data-dismiss="alert">&#215;</button>
#{messages}
</div>
HTML
    html.html_safe
  end

end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blog/index.html.erb
<div class="page-title">
	<i class="icon-comments page-title-icon"></i>
	<h2>Blog</h2>
</div>
	<!-- Blog text Text -->
	<h4> <td>A brief introduction</td> </h4>
	<p>
	<td>My name is Jurgens Smit. My background is in System
	Engineering. I'm originally I’m from Cape Town, South Africa. I enjoy travelling,
	solving problems, and being outdoors.
	<br>
	<p>Currently I’m in Sydney, and I’m really enjoying exploring
	all the social and cultural aspects of the city.</p>

	<p>I believe software and the internet has an amazing ability
	to transform the world for the better. In whatever small and insignificant way
	possible, I want to be one of the people building software to bring about those
	solutions.</p>
	<br>
	<p>This blog will be dedicated to my personal journey of
	becoming a programmer.</p></td>
	</p>
	<br>
		<div class="social_blog_links">
		<a href="https://www.facebook.com/jurgens.smit"><i class="icon-facebook"></i> </a>&nbsp;
		<a href="https://twitter.com/JurgensSmit"><i class="icon-twitter"></i> </a></i> &nbsp;
		<a href="https://plus.google.com/101612517160357782271/posts"><i class="icon-google-plus"></i> </a></i> &nbsp;
		<a href="https://github.com/JurgensSmit"><i class="icon-github"></i> </a></i> &nbsp;
		</div>
	<h4> Why Sydney Dev Camp? </h4>
	<p>
	I’m strongly motivated by a desire to learn and better
	myself in everything I do.

	</p><p>I tried learning online, through books and a lot of really
	good resources. I found out that wasn’t the right approach for me. It was hard
	to keep motivated.</p>

	<p>Nothing is comparable to setting your life aside and moving
	to another continent to immerse yourself in learning a new skill for 10 weeks.
	It is amazing being with likeminded people who are trying to change their lives
	and being part of a great community.</p>

	<p>The most exciting thing is that I have the ability to change
	the world, from my keyboard. This is how I came to be at Sydney Dev Camp.</p>
	<p></p>
	<br>
		<div class="social_blog_links">
		<a href="https://www.facebook.com/jurgens.smit"><i class="icon-facebook"></i> </a>&nbsp;
		<a href="https://twitter.com/JurgensSmit"><i class="icon-twitter"></i> </a></i> &nbsp;
		<a href="https://plus.google.com/101612517160357782271/posts"><i class="icon-google-plus"></i> </a></i> &nbsp;
		<a href="https://github.com/JurgensSmit"><i class="icon-github"></i> </a></i> &nbsp;
		</div>
	<h4> Sydney </h4>
	<p>
	I like to seek out and pursue experiences and I’m really
	enjoying all the social and cultural aspects Sydney has to offer.
	<p>I don’t always realize I’m in Sydney, since I spend most of my time coding. I’ve been exploring the city on the odd day, including a trip to
	the Blue Mountains. I’ve been extremely fortunate in meeting amazing people and
	sharing unforgettable adventures with them.</p>

	<p>I don’t think I’ll ever get used to the fact that it rains
	most days and the bizarre sounds of the birds. I’m currently investigating the
	awful sound in the morning; I think it’s a crow.</p>
	<br>
	    <%= image_tag "http://i.imgur.com/lloMaMR.jpg"%>
	    <br>
	    <br>

		<div class="social_blog_links">
		<a href="https://www.facebook.com/jurgens.smit"><i class="icon-facebook"></i> </a>&nbsp;
		<a href="https://twitter.com/JurgensSmit"><i class="icon-twitter"></i> </a></i> &nbsp;
		<a href="https://plus.google.com/101612517160357782271/posts"><i class="icon-google-plus"></i> </a></i> &nbsp;
		<a href="https://github.com/JurgensSmit"><i class="icon-github"></i> </a></i> &nbsp;
		</div>
	<h4> My Experiences So Far </h4>
	<p>
	I wake up and can’t wait to get to Sydney Dev Camp.

	</p><p>I’m consistently being pushed to my limits, learning more
	than ever before all while having more fun than I ever thought possible.</p>

	<p>My experience overall has been great. I have learned more
	than I thought was possible, I have made friends for life and have worked on
	various interesting projects.</p>

	<p><br></p>

	<p><em>I want to do more, to be more
	and to build more.</em></p>
	<p></p>
		<div class="social_blog_links">
		<a href="https://www.facebook.com/jurgens.smit"><i class="icon-facebook"></i> </a>&nbsp;
		<a href="https://twitter.com/JurgensSmit"><i class="icon-twitter"></i> </a></i> &nbsp;
		<a href="https://plus.google.com/101612517160357782271/posts"><i class="icon-google-plus"></i> </a></i> &nbsp;
		<a href="https://github.com/JurgensSmit"><i class="icon-github"></i> </a></i> &nbsp;
		</div>
	<h4>Week 3 </h4>
	<p>

	<em>It has been 3 weeks since I started the program, it seems like I have
	been here for months.</em>

	</p><p>I am putting in 12+ hours a day of coding and the only thing that makes it
	possible is the fact that I am surrounded with people with the same passion for
	learning that I have. I am completely focused on the course and putting
	everything into it.</p>

	<p>There will always be something new to learn, some new technology or a new
	technique to take advantage of. This is only the beginning.</p>
	<br>
	<p><em><b>Understanding when to work
	long hours and when to take it easy is definitely a learning process</b>.</em>

	</br>
	    <%= image_tag "http://i.imgur.com/8LBOUaz.jpg"%>
		<div class="social_blog_links">
		<a href="https://www.facebook.com/jurgens.smit"><i class="icon-facebook"></i> </a>&nbsp;
		<a href="https://twitter.com/JurgensSmit"><i class="icon-twitter"></i> </a></i> &nbsp;
		<a href="https://plus.google.com/101612517160357782271/posts"><i class="icon-google-plus"></i> </a></i> &nbsp;
		<a href="https://github.com/JurgensSmit"><i class="icon-github"></i> </a></i> &nbsp;
		</div>
	 <h4>Another productive week! </h4>
	<p>

	<p>I have several personal projects which I’m working on during my spare time. <a href="http://smitter.herokuapp.com/">Smitter </a> and <a href="http://smitbook.herokuapp.com/">Smitbook</a> will soon be replacing Twitter and Facebook if everything goes according to plan.</p>

	</p><p>We’ve been collaborating together using Github and getting more used to Test-driven development , which I’ve been enjoying quite a bit. We’re starting to dive deeper into more advanced Ruby on Rails concepts. I’m still trying to get my head around some of the more complicated topics, including database relationships.</p>

	<p>This week was challenging, but I feel confident about the weeks ahead.</p>
	<br>
	<p><em><b>Watch out Facebook and Twitter!</b></em>

		<div class="social_blog_links">
		<a href="https://www.facebook.com/jurgens.smit"><i class="icon-facebook"></i> </a>&nbsp;
		<a href="https://twitter.com/JurgensSmit"><i class="icon-twitter"></i> </a></i> &nbsp;
		<a href="https://plus.google.com/101612517160357782271/posts"><i class="icon-google-plus"></i> </a></i> &nbsp;
		<a href="https://github.com/JurgensSmit"><i class="icon-github"></i> </a></i> &nbsp;
		</div>
			 <h4>Angelhack</h4>
	<p>

	<p>I had the chance to attend Angelhack Sydney this weekend, where I worked on Mizzy. A platform which enables music lovers to connect with teachers, giving them an opportunity to learn an instrument through Google Hangouts.</p>

	</p><p>We had some challenges and we weren’t quite sure what to expect since this was our first time attending Angelhack. We could’ve planned and tested our idea better beforehand and polished our presentation a bit. I think we were more concerned with the technology and not about the fact that people want shiny and ultimately judge with their eyes.</p>

	<p>It’s amazing what we achieved in under 24 hours and I’m extremely happy with the outcome. I got a Blackberry z10 for our efforts. Score!</p>
	<br>
	<p>Overall it was a great experience and I can’t wait for the next one!</p>

		<div class="social_blog_links">
		<a href="https://www.facebook.com/jurgens.smit"><i class="icon-facebook"></i> </a>&nbsp;
		<a href="https://twitter.com/JurgensSmit"><i class="icon-twitter"></i> </a></i> &nbsp;
		<a href="https://plus.google.com/101612517160357782271/posts"><i class="icon-google-plus"></i> </a></i> &nbsp;
		<a href="https://github.com/JurgensSmit"><i class="icon-github"></i> </a></i> &nbsp;
		</div>
			 <h4>Projects</h4>
	<p>

	<p>I’ve been replicating my favorite websites in an effort to learn Ruby on Rails better, I can’t think of a better way to learn. I think it is important doing something you genuinely enjoy, otherwise you’re just wasting your time and it’ll show in your work.</p>

	</p><p>Some might say I spend way too much time on Reddit, so I thought it’ll be a good idea to make my own version of it – <a href="http://smitted.herokuapp.com/">Smitted</a>. I’m sure I’ll have it filled with cat videos soon.</p>

	<p>I’ve also been working on <a href="http://smithub.herokuapp.com/">Smithub</a>, which was created using the Github API to generate a score based on the events feed.</p>
	<br>


		<div class="social_blog_links">
		<a href="https://www.facebook.com/jurgens.smit"><i class="icon-facebook"></i> </a>&nbsp;
		<a href="https://twitter.com/JurgensSmit"><i class="icon-twitter"></i> </a></i> &nbsp;
		<a href="https://plus.google.com/101612517160357782271/posts"><i class="icon-google-plus"></i> </a></i> &nbsp;
		<a href="https://github.com/JurgensSmit"><i class="icon-github"></i> </a></i> &nbsp;
		</div>
</div>

app/views/contact/new.html.erb
    <!-- Page Title -->
    <div class="page-title">
        <i class="icon-envelope-alt page-title-icon"></i>
        <h2>Contact me</h2>
    </div>
        <!-- Contact Us -->
        <div class="contact-us container">
            <div class="row">
                <div class="contact-form span5">
                    <%= form_for @message, :url => contact_path do |form| %>
                <fieldset class="fields">
                        <div class="field">
                            <%= form.label :name %>
                            <%= form.text_field :name, :placeholder => "Enter your name...", :autofocus => true %>
                        </div>
                        <div class="field">
                            <%= form.label :email %>
                            <%= form.text_field :email, :placeholder => "Enter your email..." %>
                        </div>
                        <div class="field">
                            <%= form.label :subject %>
                            <%= form.text_field :subject, :placeholder => "Your subject..." %>
                        </div>
                        <div class="field">
                            <%= form.label :Message %>
                            <%= form.text_area :body, :placeholder => "Your message..." %>
                        </div>
                    </fieldset>
                    <fieldset class="actions">
                    <%= form.submit "Send" %>
                    </fieldset>
                    <% end %>
                    </div>
                <div class="contact-address span2">
                    <h4>I am here</h4>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d403200.04142967984!2d145.07961605!3d-37.860282850000004!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad646b5d2ba4df7%3A0x4045675218ccd90!2sMelbourne+VIC!5e0!3m2!1sen!2sau!4v1388492431962" width="500" height="450" frameborder="0" style="border:0"></iframe>
                </div>
            </div>
        </div>

app/views/home/index.html.erb
<%= image_tag "Jurgens.jpg"%>
    <br>
    <br>
    <p>
    <br>I enjoy taking complex problems and turning them into simple and beautiful solutions. I consider myself to be extremely fortunate, because my ‘job’, such as it is, simply entails doing what I love. I embrace the nerd.</br>
    <br>I like long walks on the beach, sunsets, teddy bears, kittens, rainbows and newborn babies. No, seriously. I do. Well, maybe just kittens. Ha!</p>
    <br>

        <div class="social_blog_links">
        <a href="https://www.facebook.com/jurgens.smit"><i class="icon-facebook"></i> </a>&nbsp;
        </div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<div class="container">
    <div class="header row">
        <div class="span11">
            <div class="navbar">
                <div class="navbar-inner">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </a>
                <ul class = "span6">
                <br>
                <%= link_to image_tag("logo.png"), root_path %>
                </il>
                </ul>
                <ul class="nav pull-right">
                <li>
                <a href="/home"><i class="icon-home"></i><br />Home</a>
                </li>
                <li>
                <a href="/contact"><i class="icon-envelope-alt"></i><br />Contact</a>
                </li>
                </ul>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<!-- Favicon -->
<% favicon_link_tag "favicon.ico" %>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-40504565-1', 'jurgenssmit.com');
        ga('send', 'pageview');
    </script>
<meta charset="utf-8">
<title>&middot;Jurgens Smit</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Personal website of Jurgens Smit.">
<meta name="keywords" content="Ruby, Rails, Ruby on Rails, web designer, back end developer, Jurgens Smit, sydney, front end developer, Javascript, HTML, CSS" />
<meta name="author" content="Jurgens Smit">

<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,400">
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Droid+Sans">
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Lobster">

<%= stylesheet_link_tag "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>

<%= yield(:head) %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
    <nav class="navbar-row">
      <div class="container">
      <%= render 'layouts/navigation' %>
        </div>
        </nav>
          </div>
          <div id="main" role="main">
            <div class="container">
              <div style="align: center;">
                    <div class="span8 offset2">
              <%= render 'layouts/messages' %>
                  <div class="about-us-text">
                  <%= yield %>
                  </div>
                  </div>
                  </div>
                  </div> <!--! end of .container -->
              </div> <!--! end of #main -->
            <footer>
            <div class="footer-border"></div>
          <div class="row">
        <br>
        <div class="copyright span4">
        <p> Copyright 2014 - Jurgens Smit.</p>
      </div>
    </div>
</footer>
</body>
</html>